name: MultiArchDockerBuild

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_multi_arch_image:
    name: Build multi-arch Docker image.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout builder repo
        uses: actions/checkout@v2

      - name: Clone Commento repo
        id: clone_commento
        run: |
          git clone https://gitlab.com/commento/commento.git

      - name: Change Dockerfile to use specific Node version for ARM compatability
        id: sed_dockerfile
        run: |
          sed -i 's/node:12-alpine/node:14-alpine3.12/g' commento/Dockerfile
          sed -i 's/ca-certificates/ca-certificates wget libc6-compat/g' commento/Dockerfile
          sed -i 's/ARG RELEASE=prod/ARG RELEASE=prod\nCOPY .\/resources\/ \//g' commento/Dockerfile
          sed -i 's/\/commento\/commento/\/docker-entrypoint.sh/g' commento/Dockerfile

      - name: Copy resources into build folder
        id: copy_resources
        run: |
          mkdir -p ./commento/resources
          cp ./resources/docker-entrypoint.sh ./commento/resources/docker-entrypoint.sh
          cat ./resources/docker-entrypoint.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Commento-ARM
        id: docker_build_commento_arm
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            nowaidavid/commento-arm:${{ github.sha }}
            nowaidavid/commento-arm:latest
          platforms: linux/arm64
          context: ./commento

      - name: Image digest
        run: echo ${{ steps.docker_build_commento_arm.outputs.digest }}
